
export type QuizQuestion = {
  id: number;
  question: string;
  options: string[];
  answer: string;
  category: 'JavaScript' | 'Python' | 'HTML/CSS' | 'General CS' | 'C++';
  explanation: string;
  difficulty: 'easy' | 'medium' | 'hard';
};

export const quizData: QuizQuestion[] = [
  // JavaScript
  {
    id: 1,
    question: "Which keyword is used to declare a variable that cannot be reassigned?",
    options: ["let", "var", "const", "static"],
    answer: "const",
    category: 'JavaScript',
    explanation: "`const` declares a block-scoped variable, but its value can't be reassigned. `let` is also block-scoped but can be reassigned. `var` is function-scoped.",
    difficulty: 'easy',
  },
  {
    id: 2,
    question: "What does `===` operator check for?",
    options: ["Value only", "Type only", "Value and type", "None of the above"],
    answer: "Value and type",
    category: 'JavaScript',
    explanation: "The strict equality operator `===` checks for both value and type equality without performing type coercion. The `==` operator performs type coercion before comparison.",
    difficulty: 'easy',
  },
  {
    id: 3,
    question: "What is a closure in JavaScript?",
    options: ["A function having access to the parent scope, even after the parent function has closed", "A way to close the browser window", "A built-in data structure", "A type of loop"],
    answer: "A function having access to the parent scope, even after the parent function has closed",
    category: 'JavaScript',
    explanation: "A closure gives you access to an outer function’s scope from an inner function. In JavaScript, closures are created every time a function is created.",
    difficulty: 'hard',
  },
  {
    id: 4,
    question: "Which method is used to add a new element to the end of an array?",
    options: ["shift()", "unshift()", "push()", "pop()"],
    answer: "push()",
    category: 'JavaScript',
    explanation: "`push()` adds one or more elements to the end of an array and returns the new length. `pop()` removes the last element.",
    difficulty: 'easy',
  },
  {
    id: 5,
    question: "What does `NaN` stand for?",
    options: ["Not a Node", "No Available Number", "Not a Number", "New assigned Number"],
    answer: "Not a Number",
    category: 'JavaScript',
    explanation: "`NaN` is a property of the global object. It is a value representing Not-A-Number, which often results from invalid mathematical operations.",
    difficulty: 'easy',
  },
  // Python
  {
    id: 6,
    question: "Which data structure in Python is immutable?",
    options: ["List", "Dictionary", "Set", "Tuple"],
    answer: "Tuple",
    category: 'Python',
    explanation: "Tuples are ordered, immutable collections of objects. Once a tuple is created, you cannot change its values. Lists, dictionaries, and sets are mutable.",
    difficulty: 'medium',
  },
  {
    id: 7,
    question: "What is the output of `print(2 ** 3)`?",
    options: ["6", "8", "9", "5"],
    answer: "8",
    category: 'Python',
    explanation: "The `**` operator in Python is used for exponentiation. `2 ** 3` means 2 raised to the power of 3, which is 8.",
    difficulty: 'easy',
  },
  {
    id: 8,
    question: "How do you start a single-line comment in Python?",
    options: ["//", "/*", "#", "<!--"],
    answer: "#",
    category: 'Python',
    explanation: "In Python, the hash symbol `#` is used to start a single-line comment. Any text after the `#` on that line is ignored by the interpreter.",
    difficulty: 'easy',
  },
  {
    id: 9,
    question: "What is a 'list comprehension' in Python?",
    options: ["A way to create lists using a `for` loop inside `[]`", "A built-in function for sorting lists", "A method to check if an item is in a list", "A special type of list"],
    answer: "A way to create lists using a `for` loop inside `[]`",
    category: 'Python',
    explanation: "List comprehensions provide a concise way to create lists. For example, `[x*x for x in range(5)]` creates `[0, 1, 4, 9, 16]`.",
    difficulty: 'medium',
  },
  {
    id: 10,
    question: "Which keyword is used to define a function in Python?",
    options: ["func", "function", "def", "define"],
    answer: "def",
    category: 'Python',
    explanation: "The `def` keyword is used to create, or define, a function in Python. It is followed by the function name and parentheses.",
    difficulty: 'easy',
  },
  // HTML/CSS
  {
    id: 11,
    question: "What does HTML stand for?",
    options: ["Hyper Text Markup Language", "High-level Text Machine Language", "Hyperlinks and Text Markup Language", "Home Tool Markup Language"],
    answer: "Hyper Text Markup Language",
    category: 'HTML/CSS',
    explanation: "HTML is the standard markup language for documents designed to be displayed in a web browser.",
    difficulty: 'easy',
  },
  {
    id: 12,
    question: "Which CSS property is used to change the background color of an element?",
    options: ["color", "bgcolor", "background-color", "background"],
    answer: "background-color",
    category: 'HTML/CSS',
    explanation: "The `background-color` property specifically sets the background color of an element. The `background` shorthand property can also be used.",
    difficulty: 'easy',
  },
  {
    id: 13,
    question: "What is the CSS 'box model'?",
    options: ["A model for creating 3D shapes", "A box that wraps every HTML element, consisting of: margins, borders, padding, and the actual content", "A JavaScript library for layout", "A type of HTML tag"],
    answer: "A box that wraps every HTML element, consisting of: margins, borders, padding, and the actual content",
    category: 'HTML/CSS',
    explanation: "The CSS box model is a fundamental concept. It's essentially a box that wraps around every HTML element and defines its layout and spacing.",
    difficulty: 'medium',
  },
  {
    id: 14,
    question: "Which HTML tag is used to create a hyperlink?",
    options: ["<link>", "<a>", "<href>", "<p>"],
    answer: "<a>",
    category: 'HTML/CSS',
    explanation: "The `<a>` (anchor) tag is used to create hyperlinks. The `href` attribute within the `<a>` tag specifies the URL of the page the link goes to.",
    difficulty: 'easy',
  },
  {
    id: 15,
    question: "How do you select an element with id 'header' in CSS?",
    options: [".header", "#header", "header", "*header"],
    answer: "#header",
    category: 'HTML/CSS',
    explanation: "In CSS, the hash `#` symbol is used as an ID selector. The period `.` is used for class selectors, and the element name is used for type selectors.",
    difficulty: 'easy',
  },
  // General CS
  {
    id: 16,
    question: "What does 'API' stand for?",
    options: ["Application Programming Interface", "Automated Program Interaction", "Algorithmic Protocol Interface", "Application Process Integration"],
    answer: "Application Programming Interface",
    category: 'General CS',
    explanation: "An API is a set of rules and protocols that allows different software applications to communicate with each other.",
    difficulty: 'easy',
  },
  {
    id: 17,
    question: "Which data structure uses a Last-In, First-Out (LIFO) approach?",
    options: ["Queue", "Stack", "Linked List", "Tree"],
    answer: "Stack",
    category: 'General CS',
    explanation: "A stack is an abstract data type that serves as a collection of elements, with two principal operations: push, which adds an element to the collection, and pop, which removes the most recently added element.",
    difficulty: 'medium',
  },
  {
    id: 18,
    question: "What is the time complexity of a binary search algorithm?",
    options: ["O(n)", "O(log n)", "O(n^2)", "O(1)"],
    answer: "O(log n)",
    category: 'General CS',
    explanation: "Binary search works by repeatedly dividing the search interval in half. This logarithmic time complexity makes it very efficient for searching sorted arrays.",
    difficulty: 'medium',
  },
  {
    id: 19,
    question: "What is 'git'?",
    options: ["A programming language", "A text editor", "A distributed version control system", "A type of server"],
    answer: "A distributed version control system",
    category: 'General CS',
    explanation: "Git is a version control system used for tracking changes in source code during software development. It's designed for coordinating work among programmers.",
    difficulty: 'easy',
  },
  {
    id: 20,
    question: "In object-oriented programming, what is inheritance?",
    options: ["The ability of an object to take on many forms", "A mechanism where a new class inherits properties and behavior from an existing class", "Bundling data and methods that operate on the data into a single unit", "Hiding the internal state and requiring all interaction to be done through an object's methods"],
    answer: "A mechanism where a new class inherits properties and behavior from an existing class",
    category: 'General CS',
    explanation: "Inheritance is a core OOP concept that allows a new class (subclass) to be based on an existing class (superclass), inheriting its attributes and methods.",
    difficulty: 'medium',
  },
   // C++
  {
    id: 21,
    question: "How do you declare a pointer in C++?",
    options: ["ptr<int> p;", "int &p;", "int *p;", "int p*;"],
    answer: "int *p;",
    category: 'C++',
    explanation: "In C++, an asterisk `*` is used after the data type to declare a pointer. `int *p;` declares a pointer `p` that can hold the address of an integer variable.",
    difficulty: 'easy',
  },
  {
    id: 22,
    question: "What is the main difference between a `struct` and a `class` in C++?",
    options: ["Structs cannot have methods", "Class members are public by default, while struct members are private", "Structs are for primitive types only", "Class members are private by default, while struct members are public"],
    answer: "Class members are private by default, while struct members are public",
    category: 'C++',
    explanation: "The only difference is the default access specifier. For a `class`, members are `private` by default. For a `struct`, members are `public` by default.",
    difficulty: 'hard',
  },
  {
    id: 23,
    question: "Which keyword is used to deallocate memory that was allocated with `new`?",
    options: ["free", "remove", "delete", "clear"],
    answer: "delete",
    category: 'C++',
    explanation: "The `delete` operator is used in C++ to release the memory allocated by the `new` operator. For arrays allocated with `new[]`, you must use `delete[]`.",
    difficulty: 'medium',
  },
  {
    id: 24,
    question: "What is function overloading in C++?",
    options: ["Defining multiple functions with the same name but different parameters", "Overriding a function in a derived class", "A function that can call itself", "A function that has too many arguments"],
    answer: "Defining multiple functions with the same name but different parameters",
    category: 'C++',
    explanation: "Function overloading allows you to have multiple functions with the same name, as long as they have a different number of arguments or different types of arguments.",
    difficulty: 'medium',
  },
  {
    id: 25,
    question: "What does STL stand for in C++?",
    options: ["Standard Template Library", "Static Type Language", "System Tool Library", "Standard Transaction Logic"],
    answer: "Standard Template Library",
    category: 'C++',
    explanation: "The STL is a set of C++ template classes to provide common programming data structures and functions such as lists, stacks, arrays, etc.",
    difficulty: 'medium',
  },
  // More questions
   {
    id: 26,
    question: "Which JavaScript framework is known for its virtual DOM?",
    options: ["Angular", "Vue", "React", "Svelte"],
    answer: "React",
    category: 'JavaScript',
    explanation: "React uses a virtual DOM to efficiently update the UI. It keeps a lightweight copy of the real DOM and only updates the parts that have changed.",
    difficulty: 'medium',
  },
  {
    id: 27,
    question: "What is the purpose of the `finally` block in a `try...catch...finally` statement?",
    options: ["To execute code if an error occurs", "To execute code regardless of whether an error occurred or not", "To declare the final value of a variable", "To catch specific types of errors"],
    answer: "To execute code regardless of whether an error occurred or not",
    category: 'JavaScript',
    explanation: "The `finally` block always executes after the `try` and `catch` blocks have completed. It is often used for cleanup code.",
    difficulty: 'medium',
  },
  {
    id: 28,
    question: "What does the `pass` statement do in Python?",
    options: ["It skips the current iteration of a loop", "It terminates the program", "It is a placeholder and does nothing", "It raises an exception"],
    answer: "It is a placeholder and does nothing",
    category: 'Python',
    explanation: "The `pass` statement is a null operation. It is used when a statement is syntactically required but you don't want any command or code to execute.",
    difficulty: 'easy',
  },
  {
    id: 29,
    question: "What is a decorator in Python?",
    options: ["A way to add styling to text", "A function that takes another function and extends its behavior without explicitly modifying it", "A special type of comment", "A variable with a fixed value"],
    answer: "A function that takes another function and extends its behavior without explicitly modifying it",
    category: 'Python',
    explanation: "Decorators are a powerful feature in Python that allow programmers to modify the behavior of a function or class. They are often used for logging, timing, and authorization.",
    difficulty: 'hard',
  },
  {
    id: 30,
    question: "What is the purpose of the `<!DOCTYPE html>` declaration?",
    options: ["It defines the character set of the document", "It is a comment", "It tells the browser that the document is an HTML5 document", "It links to an external stylesheet"],
    answer: "It tells the browser that the document is an HTML5 document",
    category: 'HTML/CSS',
    explanation: "The DOCTYPE declaration is an instruction to the web browser about what version of HTML the page is written in. `<!DOCTYPE html>` is for HTML5.",
    difficulty: 'easy',
  },
  {
    id: 31,
    question: "What is the correct syntax for a `for` loop in C++?",
    options: ["for (i = 0; i < 5; i++)", "for i in 1 to 5", "for (i < 5; i++)", "for (i = 0; i < 5)"],
    answer: "for (i = 0; i < 5; i++)",
    category: 'C++',
    explanation: "The standard C-style for loop syntax includes initialization, condition, and increment/decrement parts within the parentheses.",
    difficulty: 'easy',
  },
  {
    id: 32,
    question: "What is polymorphism?",
    options: ["A type of data structure", "The ability of a message to be displayed in many forms", "A way to store multiple values in one variable", "A feature of object-oriented programming"],
    answer: "The ability of a message to be displayed in many forms",
    category: 'General CS',
    explanation: "Polymorphism allows objects of different classes to respond to the same message (method call) in different ways, which is a core concept in OOP.",
    difficulty: 'medium',
  },
  {
    id: 33,
    question: "Which of the following is NOT a valid CSS selector?",
    options: ["#myId", ".myClass", "$myElement", "div"],
    answer: "$myElement",
    category: 'HTML/CSS',
    explanation: "The '$' symbol is not a standard CSS selector. '#' is for IDs, '.' is for classes, and element names (like 'div') are type selectors.",
    difficulty: 'easy',
  },
  {
    id: 34,
    question: "What will `[1, 2, 3].map(num => num * 2)` return in JavaScript?",
    options: ["[2, 4, 6]", "[1, 2, 3, 1, 2, 3]", "[1, 4, 9]", "Error"],
    answer: "[2, 4, 6]",
    category: 'JavaScript',
    explanation: "The `map` method creates a new array by applying a function to each element of the original array. In this case, it doubles each number.",
    difficulty: 'easy',
  },
  {
    id: 35,
    question: "What is the primary purpose of a constructor in Python classes?",
    options: ["To destroy an object", "To initialize the object's state", "To create a copy of the object", "To define the class methods"],
    answer: "To initialize the object's state",
    category: 'Python',
    explanation: "The `__init__` method is the constructor in Python. It's called when a new object is created and is used to set up its initial attributes.",
    difficulty: 'medium',
  },
  {
    id: 36,
    question: "Which of the following data types is not built-in in C++?",
    options: ["int", "string", "float", "char"],
    answer: "string",
    category: 'C++',
    explanation: "`std::string` is part of the C++ Standard Library, not a fundamental built-in type like `int`, `float`, or `char`. You need to include the `<string>` header.",
    difficulty: 'hard',
  },
  {
    id: 37,
    question: "Which data structure is typically used to implement a priority queue?",
    options: ["Stack", "Queue", "Heap", "Linked List"],
    answer: "Heap",
    category: 'General CS',
    explanation: "A Heap is a specialized tree-based data structure that satisfies the heap property, making it ideal for efficiently finding the item with the highest (or lowest) priority.",
    difficulty: 'hard',
  },
  {
    id: 38,
    question: "What does the `flex-grow` property do in CSS Flexbox?",
    options: ["It sets the initial size of a flex item.", "It allows a flex item to grow if there is extra space.", "It allows a flex item to shrink if needed.", "It aligns items along the main axis."],
    answer: "It allows a flex item to grow if there is extra space.",
    category: 'HTML/CSS',
    explanation: "`flex-grow` dictates how much of the remaining space in the flex container should be assigned to the item. A value of 0 means it won't grow.",
    difficulty: 'medium',
  },
  {
    id: 39,
    question: "What is the result of `\"hello\"[1]` in JavaScript?",
    options: ["\"h\"", "Error", "\"e\"", "undefined"],
    answer: "\"e\"",
    category: 'JavaScript',
    explanation: "Strings in JavaScript can be treated like arrays of characters, so bracket notation can be used to access a character at a specific index.",
    difficulty: 'easy',
  },
  {
    id: 40,
    question: "How do you get the number of items in a list in Python?",
    options: ["list.size()", "list.length", "size(list)", "len(list)"],
    answer: "len(list)",
    category: 'Python',
    explanation: "The built-in `len()` function is used to get the number of items in a collection, including lists, tuples, and dictionaries.",
    difficulty: 'easy',
  },
  {
    id: 41,
    question: "What is a 'null pointer exception'?",
    options: ["An error from dividing by zero", "An error from accessing a memory location that doesn't exist", "An error when a program tries to use a reference that points to no object (null)", "An error in the C++ compiler"],
    answer: "An error when a program tries to use a reference that points to no object (null)",
    category: 'General CS',
    explanation: "This common runtime error occurs when you try to access members (like methods or fields) of a variable that hasn't been initialized with an object.",
    difficulty: 'medium',
  },
  {
    id: 42,
    question: "What is the purpose of the `&` symbol in a C++ declaration like `int &ref = x;`?",
    options: ["It declares a pointer", "It gets the memory address of x", "It creates a reference to x", "It performs a bitwise AND operation"],
    answer: "It creates a reference to x",
    category: 'C++',
    explanation: "In a declaration, `&` creates a reference, which is an alias for an existing variable. `ref` and `x` will refer to the same memory location.",
    difficulty: 'medium',
  },
  {
    id: 43,
    question: "Which HTML tag defines the main content of a document?",
    options: ["<main>", "<body>", "<content>", "<article>"],
    answer: "<body>",
    category: 'HTML/CSS',
    explanation: "The `<body>` tag contains all the visible content of an HTML document, such as headings, paragraphs, images, etc. `<main>` is used for the primary content, but it resides within the `<body>`.",
    difficulty: 'easy',
  },
  {
    id: 44,
    question: "What is a 'Promise' in JavaScript?",
    options: ["A guarantee that a function will not have errors", "An object representing the eventual completion or failure of an asynchronous operation", "A type of callback function", "A syntax for declaring variables"],
    answer: "An object representing the eventual completion or failure of an asynchronous operation",
    category: 'JavaScript',
    explanation: "Promises are fundamental for handling asynchronous actions in modern JavaScript, allowing you to chain operations that depend on the result of a previous async task.",
    difficulty: 'hard',
  },
  {
    id: 45,
    question: "What is the difference between a list and a dictionary in Python?",
    options: ["Lists are mutable, dictionaries are not", "Lists are ordered, dictionaries are unordered (in older Python versions)", "Lists use integer indices, dictionaries use keys", "All of the above"],
    answer: "Lists use integer indices, dictionaries use keys",
    category: 'Python',
    explanation: "The primary difference is how they are indexed. Lists are accessed by numerical index (0, 1, 2...), while dictionaries are accessed by a unique key (like a string). Both are mutable.",
    difficulty: 'medium',
  },
  {
    id: 46,
    question: "What does 'TCP/IP' stand for?",
    options: ["Telecommunication Control Protocol/Internet Protocol", "Transmission Control Protocol/Internet Protocol", "Text and Code Protocol/Inter-network Protocol", "Transmission Connection Procedure/Internet Path"],
    answer: "Transmission Control Protocol/Internet Protocol",
    category: 'General CS',
    explanation: "TCP/IP is the foundational suite of communication protocols used to interconnect network devices on the internet.",
    difficulty: 'medium',
  },
  {
    id: 47,
    question: "What is the role of a 'header file' in C++?",
    options: ["It contains the main logic of the program", "It defines function and class declarations that can be shared among multiple source files", "It's where you store comments and documentation", "It is automatically generated by the compiler"],
    answer: "It defines function and class declarations that can be shared among multiple source files",
    category: 'C++',
    explanation: "Header files (`.h` or `.hpp`) are used to declare interfaces (like function prototypes and class definitions) so they can be included and used in different `.cpp` files, promoting modularity.",
    difficulty: 'medium',
  },
  {
    id: 48,
    question: "Which CSS property controls the stacking order of elements?",
    options: ["order", "stack-index", "layer", "z-index"],
    answer: "z-index",
    category: 'HTML/CSS',
    explanation: "`z-index` specifies the stack order of a positioned element. An element with a greater stack order is always in front of an element with a lower stack order.",
    difficulty: 'medium',
  },
  {
    id: 49,
    question: "How do you handle an event in React?",
    options: ["Using addEventListener in the HTML", "By passing a function as a prop like `onClick={myFunction}`", "By using the `<event>` tag", "Events are handled automatically"],
    answer: "By passing a function as a prop like `onClick={myFunction}`",
    category: 'JavaScript',
    explanation: "React has its own event handling system that is very similar to handling events on DOM elements, but with a camelCase naming convention (e.g., `onClick`).",
    difficulty: 'easy',
  },
  {
    id: 50,
    question: "What does the `if __name__ == '__main__':` block do in Python?",
    options: ["It's a mandatory part of every Python script", "It defines the main function", "It allows code to be run only when the file is executed directly, not when imported", "It checks if the script is running on the main server"],
    answer: "It allows code to be run only when the file is executed directly, not when imported",
    category: 'Python',
    explanation: "This is a common Python idiom. The code inside this block will only execute if the script is run as the main program, making it useful for tests or entry points.",
    difficulty: 'hard',
  },
  {
    id: 51,
    question: "What is the purpose of `virtual` keyword in C++?",
    options: ["To declare a function that does not exist", "To enable dynamic dispatch or runtime polymorphism", "To make a variable constant", "To create a virtual memory space"],
    answer: "To enable dynamic dispatch or runtime polymorphism",
    category: 'C++',
    explanation: "The `virtual` keyword on a base class method allows a derived class to provide its own implementation, which will be called even through a base class pointer.",
    difficulty: 'hard',
  },
  {
    id: 52,
    question: "Which algorithm is NOT a sorting algorithm?",
    options: ["Bubble Sort", "Quick Sort", "Dijkstra's Algorithm", "Merge Sort"],
    answer: "Dijkstra's Algorithm",
    category: 'General CS',
    explanation: "Dijkstra's algorithm is used for finding the shortest paths between nodes in a graph. The others are all algorithms for sorting elements in a list.",
    difficulty: 'medium',
  },
  {
    id: 53,
    question: "What is the difference between `let` and `var` in JavaScript?",
    options: ["They are identical", "`let` is function-scoped, `var` is block-scoped", "`let` is block-scoped, `var` is function-scoped", "`var` cannot be reassigned"],
    answer: "`let` is block-scoped, `var` is function-scoped",
    category: 'JavaScript',
    explanation: "`let` and `const` (block-scoped) were introduced in ES6 to solve common problems associated with the function-scoped `var`, like issues in loops.",
    difficulty: 'medium',
  },
  {
    id: 54,
    question: "What is the purpose of the `self` parameter in Python class methods?",
    options: ["It refers to the parent class", "It is a reference to the current instance of the class", "It's an optional parameter for documentation", "It refers to the global scope"],
    answer: "It is a reference to the current instance of the class",
    category: 'Python',
    explanation: "`self` represents the instance of the class. By using `self`, we can access the attributes and methods of the class in Python.",
    difficulty: 'easy',
  },
  {
    id: 55,
    question: "Which of these is used to handle responsive design in CSS?",
    options: ["@media queries", "@responsive rules", "CSS Portals", "The `<responsive>` tag"],
    answer: "@media queries",
    category: 'HTML/CSS',
    explanation: "Media queries are a key part of responsive web design, allowing you to apply different CSS styles for different device characteristics, such as screen width.",
    difficulty: 'easy',
  }
];
