export const techWords = [
  "agile", "array", "async", "axiom", "azure",
  "batch", "binary", "block", "cloud", "cache",
  "cypher", "debug", "delta", "docker", "drive",
  "ether", "event", "field", "flask", "frame",
  "gates", "ghz", "git", "go", "graphql",
  "hertz", "host", "http", "hub", "hyper",
  "index", "input", "intel", "ionic",
  "java", "json", "jquery",
  "keras", "kernel", "logic", "login", "loop",
  "macro", "matrix", "merge", "micro", "modal",
  "nas", "node", "null",
  "object", "oracle",
  "parse", "patch", "pixel", "proxy", "python",
  "query", "queue",
  "react", "redis", "redux", "rest", "router", "ruby", "rust",
  "sass", "scala", "scope", "script", "sdk", "servo", "shell",
  "slice", "stack", "state", "stream", "swift", "sync",
  "table", "tensor", "token", "tree",
  "unix", "url", "user", "uuid",
  "vector", "view", "virtual", "virus", "vue",
  "web", "while", "widget", "world", "write",
  "xml",
  "yaml",
  "zsh"
];
